# .github/workflows/test.yml
name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm install --no-save @testmo/testmo-cli
      - run: |
          npx testmo automation:run:submit \
            --instance "https://testautomation69.testmo.net/automation/sources/1" \
            --project-id 1 \
            --name "Mocha test run" \
            --source "unit-tests" \
            --results results/*.xml \
            -- npm run mocha-junit # Note space after --
        env:
          TESTMO_URL: "https://testautomation69.testmo.net/automation/sources/1"
          TESTMO_TOKEN: "testmo_api_eyJpdiI6IjZEeUp4UFlydU1WbkxXWUk0azg0ZlE9PSIsInZhbHVlIjoiRzBsbDJwSHVBVGpvRGxLTnlnWGtwRlMyNldaVFFjWm40QXpDZXQ2WFNERT0iLCJtYWMiOiIzMzdlOTlmZWU0YzUwMzY2NzA1OWVkM2ZkZDAyNmNkMWFkNDc5ZmIwN2I5YzZlZWE3NWY5YWI5ODJlYTUyNTEyIiwidGFnIjoiIn0="
